# Generated by Django 4.2.4 on 2023-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0002_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
