# Generated by Django 4.2.3 on 2023-09-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0003_category_image_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
